# Generated by Django 5.1 on 2024-08-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='greeting_1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='home',
            name='greeting_2',
            field=models.CharField(max_length=30),
        ),
    ]
