# Generated by Django 5.1 on 2024-08-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='googleverfication',
            field=models.TextField(default='text'),
        ),
    ]
