name: CD-Liara
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: update-liara
        env:
          LIARA_TOKEN: ${{ secrets.LIARA_API_TOKEN }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{secrets.DEBUG}}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          npm i -g @liara/cli@5
          liara deploy --app="parsasadeghiasl" --api-token="$LIARA_TOKEN" --no-app-logs